Glue_Services/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ResponsePostProcessor.urls')),
    path('', include('django_prometheus.urls')),
]

ResponsePostProcessor/urls.py
from django.urls import path
from . import views

app_name = 'ResponsePostProcessor'

urlpatterns = [
    path('', views.home, name='home'),
    path('form/new/', views.FormCreateView.as_view(), name='form_new'),
    path('form/<int:pk>/', views.FormDetailView.as_view(), name='form_detail'),
    path('form/<int:pk>/edit/', views.FormUpdateView.as_view(), name='form_edit'),
    path('form/<int:pk>/delete/', views.FormDeleteView.as_view(), name='form_delete'),
    path('form/<int:form_pk>/question/new/', views.QuestionCreateView.as_view(), name='question_new'),
    path('form/<int:form_pk>/respond/', views.FormResponseCreateView.as_view(), name='form_respond'),
    path('form/<int:form_pk>/response/<int:pk>/', views.ResponseDetailView.as_view(), name='response_detail'),
    path('tasks/', views.PostProcessingTaskListView.as_view(), name='task_list'),
    path('tasks/create/', views.PostProcessingTaskCreateView.as_view(), name='task_create'),
]

ResponsePostProcessor/models.py
from django.db import models

# Create your models here

class PostProcessingTask(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Form(models.Model):
    GOOGLE_SHEETS = 'GS'
    POST_PROCESS_CHOICES = [
        (GOOGLE_SHEETS, 'Google Sheets'),
        # Add other post-processing tasks here as needed
    ]
    title = models.CharField(max_length=200)
    description = models.TextField()
    post_processing_tasks = models.ManyToManyField(PostProcessingTask, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    MULTIPLE_CHOICE = 'MC'
    TEXT = 'TXT'
    QUESTION_TYPE_CHOICES = [
        (MULTIPLE_CHOICE, 'Multiple Choice'),
        (TEXT, 'Text'),
    ]
    form = models.ForeignKey(Form, related_name='questions', on_delete=models.CASCADE)
    text = models.TextField()
    question_type = models.CharField(max_length=3, choices=QUESTION_TYPE_CHOICES, default=TEXT)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Response(models.Model):
    form = models.ForeignKey(Form, related_name='responses', on_delete=models.CASCADE)
    # New field to hold all answers as a JSON object
    answers = models.JSONField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_response_data(self):
        response_data = {}
        for question_id, answer in self.answers.items():
            # Split the string by underscore and take the second part as the id
            numeric_id = question_id.split('_')[1]
            question = Question.objects.get(id=numeric_id)
            response_data[question.text] = answer
        return response_data

ResponsePostProcessor/forms.py
from django import forms
from .models import Form, Question, PostProcessingTask

class FormCreateForm(forms.ModelForm):
    class Meta:
        model = Form
        fields = ['title', 'description', 'post_processing_tasks']
        widgets = {
            'post_processing_tasks': forms.CheckboxSelectMultiple,
        }

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise forms.ValidationError('The title cannot be empty.')
        return title

class PostProcessingTaskForm(forms.ModelForm):
    class Meta:
        model = PostProcessingTask
        fields = ['name', 'description']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'question_type']

class DynamicForm(forms.Form):
    def __init__(self, *args, **kwargs):
        questions = kwargs.pop('questions')
        super(DynamicForm, self).__init__(*args, **kwargs)
        for question in questions:
            self.fields[f'question_{question.id}'] = forms.CharField(label=question.text)

ResponsePostProcessor/views.py
from .models import Form, Question, Response, PostProcessingTask
from .forms import FormCreateForm, QuestionForm, DynamicForm, PostProcessingTaskForm
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import View
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def home(request):
    return render(request, 'ResponsePostProcessor/home.html')

class FormCreateView(CreateView):
    model = Form
    fields = ['title', 'description', 'post_processing_tasks']
    template_name = 'ResponsePostProcessor/form_edit.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('ResponsePostProcessor:form_detail', kwargs={'pk': self.object.pk})

class FormDetailView(DetailView):
    model = Form
    template_name = 'ResponsePostProcessor/form_detail.html'

class FormUpdateView(UpdateView):
    model = Form
    fields = ['title', 'description']
    template_name = 'ResponsePostProcessor/form_edit.html'

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('ResponsePostProcessor:form_detail', kwargs={'pk': self.object.pk})

class FormDeleteView(DeleteView):
    model = Form
    template_name = 'ResponsePostProcessor/form_confirm_delete.html'
    context_object_name = 'form'

    def get_success_url(self):
        return reverse('ResponsePostProcessor:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_id'] = self.kwargs['pk']
        return context

class QuestionCreateView(CreateView):
    model = Question
    form_class = QuestionForm
    template_name = 'ResponsePostProcessor/question_edit.html'

    def form_valid(self, form):
        form.instance.form = Form.objects.get(pk=self.kwargs['form_pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('ResponsePostProcessor:form_detail', kwargs={'pk': self.kwargs['form_pk']})

class FormResponseCreateView(View):
    template_name = 'ResponsePostProcessor/form_respond.html'

    def get(self, request, *args, **kwargs):
        form = Form.objects.get(id=kwargs.get('form_pk'))
        questions = form.questions.all()
        response_form = DynamicForm(questions=questions)
        return render(request, self.template_name, {'form': form, 'response_form': response_form})

    def post(self, request, *args, **kwargs):
        print("COMING TO POST FUNCTION AFTER A POST SUBMISSION")
        try:
            form = Form.objects.get(id=kwargs.get('form_pk'))
            questions = form.questions.all()
            response_form = DynamicForm(request.POST, questions=questions)

            if response_form.is_valid():
                response = Response.objects.create(form=form, answers=response_form.cleaned_data)
                return redirect('ResponsePostProcessor:response_detail', form_pk=form.pk, pk=response.pk)

            return render(request, self.template_name, {'form': form, 'response_form': response_form})
        except ObjectDoesNotExist as e:
            return render(request, 'ResponsePostProcessor/error.html', {'message': 'The requested form does not exist.'})
        except Exception as e:
            return render(request, 'ResponsePostProcessor/error.html', {'message': 'An error occurred while processing your request.'})

class ResponseDetailView(DetailView):
    model = Response
    template_name = 'ResponsePostProcessor/response_detail.html'
    context_object_name = 'response'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.object.form
        return context

class PostProcessingTaskListView(ListView):
    model = PostProcessingTask
    template_name = 'ResponsePostProcessor/post_processing_task_list.html'
    context_object_name = 'tasks'

class PostProcessingTaskCreateView(CreateView):
    model = PostProcessingTask
    form_class = PostProcessingTaskForm
    template_name = 'ResponsePostProcessor/post_processing_task_create.html'

    def get_success_url(self):
        return reverse('ResponsePostProcessor:task_list')

ResponsePostProcessor/templates/ResponsePostProcessor/base_generic.html
<!DOCTYPE html>
<html>
<head>
    <title>Response Post Processor</title>
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'ResponsePostProcessor:home' %}">Home</a> |
            <a href="{% url 'ResponsePostProcessor:form_new' %}">Create Form</a>
        </nav>
    </header>

    <main>
        {% block content %}

        {% endblock content %}
    </main>
</body>
</html>

ResponsePostProcessor/templates/ResponsePostProcessor/error.html
{% extends "ResponsePostProcessor/base_generic.html" %}

{% block content %}
  <h2>Error</h2>
  <p>{{ message }}</p>
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/form_confirm_delete.html
{% extends "ResponsePostProcessor/base_generic.html" %}

{% block content %}
  <h2>Delete Form</h2>
  <p>Are you sure you want to delete the form "{{ form.title }}"?</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit">Yes, delete</button>
  </form>
  <a href="{% url 'ResponsePostProcessor:form_detail' form_id %}">Cancel</a>
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/form_detail.html
{% extends 'ResponsePostProcessor/base_generic.html' %}

{% block content %}
    <h1>Form: {{ form.title }}</h1>
    <p>Description: {{ form.description }}</p>
    <p>Created at: {{ form.created_at }}</p>
    <a href="{% url 'ResponsePostProcessor:form_edit' form.id %}">Edit Form</a>
    <a href="{% url 'ResponsePostProcessor:form_delete' form.id %}">Delete Form</a>
    <a href="{% url 'ResponsePostProcessor:question_new' form.id %}">Create Question</a>
    <a href="{% url 'ResponsePostProcessor:form_respond' form.id %}">Respond</a>
    <h2>Questions in this form:</h2>
    {% for question in object.questions.all %}
        <div>
            <h3>{{ question.text }}</h3>
            <p>Type: {{ question.get_question_type_display }}</p>
        </div>
    {% empty %}
        <p>No questions in this form yet.</p>
    {% endfor %}
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/form_edit.html
{% extends "ResponsePostProcessor/base_generic.html" %}

{% block content %}
<h2>Edit Form</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    {% for field in form %}
        {% for error in field.errors %}
            <p style="color: red;">{{ error }}</p>
        {% endfor %}
    {% endfor %}
    <button type="submit">Save</button>
</form>
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/form_respond.html
{% extends 'ResponsePostProcessor/base_generic.html' %}

{% block content %}
    <h1>Answer the questions for the form "{{ form.title }}"</h1>
    <form method="POST">
        {% csrf_token %}
        {{ response_form.as_p }}
        <button type="submit">Submit answers</button>
    </form>
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/home.html
<!DOCTYPE html>
<html>
    <head>
        <title>Welcome to Glue Services</title>
    </head>
    <body>
        <h1>Welcome to Glue Services</h1>
        <p>This is the home page of our Response Post Processor application. Stay tuned for more features!</p>
        <a href="{% url 'ResponsePostProcessor:form_new' %}">
            <button>Create New Form</button>
        </a>
    </body>
</html>

ResponsePostProcessor/templates/ResponsePostProcessor/post_processing_task_create.html
{% extends "ResponsePostProcessor/base_generic.html" %}

{% block content %}
  <h2>Create post-processing task</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/post_processing_task_list.html
{% extends "ResponsePostProcessor/base_generic.html" %}

{% block content %}
  <h2>Post-processing tasks</h2>
  <ul>
    {% for task in tasks %}
      <li>{{ task.name }} - {{ task.description }}</li>
    {% empty %}
      <li>No tasks yet.</li>
    {% endfor %}
  </ul>
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/question_edit.html
{% extends "ResponsePostProcessor/base_generic.html" %}

{% block content %}
<h2>New Question</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    {% for field in form %}
        {% for error in field.errors %}
            <p style="color: red;">{{ error }}</p>
        {% endfor %}
    {% endfor %}
    <button type="submit">Save</button>
</form>
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/response_detail.html
{% extends 'ResponsePostProcessor/base_generic.html' %}

{% block content %}
    <h1>Response details</h1>
    <h2>Form: {{ form.title }}</h2>
    <ul>
        {% for question, answer in response.get_response_data.items %}
            <li>{{ question }}: {{ answer }}</li>
        {% endfor %}
    </ul>
{% endblock %}

ResponsePostProcessor/templates/ResponsePostProcessor/response_list.html
{% extends 'ResponsePostProcessor/base_generic.html' %}

{% block content %}
    <h1>Responses for the form "{{ form.title }}"</h1>
    <ul>
        {% for response in responses %}
            <li><a href="{% url 'ResponsePostProcessor:response_detail' form_pk=form.pk pk=response.pk %}">{{ response.pk }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}